name: auto_size_text_field
description: Flutter TextField widget that automatically resizes text field to fit perfectly within its bounds.
<<<<<<< HEAD
version: 2.2.3
=======
version: 2.3.2
>>>>>>> a75a3fa (feat: onTapOutside handler)
homepage: https://github.com/lzhuor/auto_size_text_field

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
